# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-15 13:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storagedevice',
            old_name='sub_aset_type',
            new_name='sub_asset_type',
        ),
    ]
